### ISSUE TITLE
BigBlueButton vs OpenMeetings

### ISSUE THREAD

**Issue by Cribstone** [mainehackerclub/open_vehicle_tracker#8]
http://www.bigbluebutton.org/ 
http://openmeetings.apache.org/

BigBlueButton appears to be the more fully featured platform, but may require more resources and bandwidth as a result.  It is a fully Open Source videoconferencing suite intended for distance learning applications, but also used for small group collaboration.  OpenMeetings might be more oriented towards our needs however.

**Comment by janewilkin** [comment]
This looks like a potentially useful platform for our mentoring & education programs as well.

**Comment by Cribstone** [comment]
BBB is definitely looking awesome! But a few obstacles remain if we want to give it a try.  
First, its has very specific hardware requirements needing- a dedicated Quad-core machine with at least 4GB of memory and a 2.6Gz Processor 
Secondly, The latest Beta version only runs on Ubuntu 10.10 64Bit (which is kind of strange that they would only test on deprecated software...)  The stable version can also run on 32Bit but otherwise has the same requirements.
It can run on a VM but performance suffers considerably.
  If we could find someone with an old Quad Core desktop they're getting rid of, it might be fun to set up our own remote server somewhere with a fast internet connection?  Perhaps even host our own LocalWiki or Wordpress off of it?
  Another option could be to rent rackspace through Code for Maine...

**Comment by Cribstone** [comment]
As this project could benefit all of our efforts and not just the OVT, I've created a new repository under Code for Maine where we can document and develop anything related to group collaboration.  Anybody is welcome to fork to Maine Hacker Club if need be.- https://github.com/Code4Maine/hackingbee
